{{- if and .Values.jellyfin.apiKey (not .Values.jellyfin.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tideline.fullname" . }}
  labels:
    {{- include "tideline.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.jellyfin.existingSecretKey }}: {{ .Values.jellyfin.apiKey | quote }}
{{- end }}
